/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dy' at '16/12/28 20:25' with Gradle 3.2.1
 *
 * @author dy, @date 16/12/28 20:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
